# Generated by Django 5.2.1 on 2026-04-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_remove_systemmodule_architecture_diagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemfeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("core", "Core Feature"),
                    ("advanced", "Advanced Feature"),
                    ("integration", "Integration"),
                    ("performance", "Performance"),
                    ("security", "Security"),
                    ("ui", "User Interface"),
                    ("visualization", "Visualization"),
                    ("data_display", "Data Display"),
                    ("user_tool", "User Tool"),
                ],
                default="core",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="systemmetric",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("performance", "Performance"),
                    ("usage", "Usage"),
                    ("uptime", "Uptime"),
                    ("response_time", "Response Time"),
                    ("throughput", "Throughput"),
                    ("error_rate", "Error Rate"),
                    ("custom", "Custom"),
                    ("development", "Development"),
                    ("technical", "Technical"),
                ],
                default="performance",
                max_length=20,
            ),
        ),
    ]
