# Generated by Django 5.2.1 on 2025-11-03 14:20

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_remove_systemlogentry_actual_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True,
                help_text="Series description with Markdown formatting support",
            ),
        ),
    ]
